DROP DATABASE IF EXISTS AUTHDB;
CREATE DATABASE AUTHDB;
GRANT ALL PRIVILEGES ON DATABASE AUTHDB TO ananth;
DROP DATABASE IF EXISTS MSG_STORAGE;
CREATE DATABASE MSG_STORAGE;
GRANT ALL PRIVILEGES ON DATABASE MSG_STORAGE TO ananth;
DROP DATABASE IF EXISTS GROUPDB;
CREATE DATABASE GROUPDB;
GRANT ALL PRIVILEGES ON DATABASE GROUPDB TO ananth;